spring:
  application:
    name: Prueba_Izertis

  r2dbc:
    url: r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ""

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

  codec:
    max-in-memory-size: 5MB

server:
  port: 8082

resilience4j:
  circuitbreaker:
    instances:
      priceService:
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 2
        slidingWindowSize: 10

app:
  security:
    user: izertisUser
    pass: izertisPass
