spring:
  application:
    name: Prueba_Izertis
  r2dbc:
    url: ${R2DBC_URL:r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
    username: ${R2DBC_USERNAME:sa}
    password: ${R2DBC_PASSWORD:""}
  sql:
    init:
      mode: ${SQL_INIT_MODE:never}
  codec:
    max-in-memory-size: ${CODEC_MAX_IN_MEMORY_SIZE:5MB}

server:
  port: ${SERVER_PORT:8082}

app:
  security:
    user: ${APP_SECURITY_USER}
    pass: ${APP_SECURITY_PASS}
